name: puc-verifica-ticket-api
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    env_file:
      - .env
    ports:
      - "5001:5001"
    volumes:
      - .:/app
    # networks:
    #   - puc-verifica-ticket-network
# networks:
#   puc-verifica-ticket-network:
#     name: puc-verifica-ticket
#     external: true
